Fix yaml indentation
The PDF build is broken right now with the message:

    Error: Missing download info for actions/upload-artifact@v3

I don't know what's causing it, but this indentation looks incorrect.